### PR TITLE
fix: Select streams by default and add new streams to docs

### LINKED ISSUE #163: Consider deselecting certain streams by default
<blockquote>

<p dir="auto">404 warning - Some endpoints are only available to privileged users, and the API appears to handle this at our site by return 404 if the endpoint is not reachable. I don't know how to handle this error properly in the Meltano SDK - the fix for me would be to "not select" the stream, e.g. I have had varying success querying <code class="notranslate">{accountId}/repositories/</code> with different API keys.</p>

</blockquote>

From https://github.com/MeltanoLabs/tap-dbt/pull/162.

Perhaps [`selected_by_default`](https://sdk.meltano.com/en/latest/classes/singer_sdk.Stream.html#singer_sdk.Stream.selected_by_default) can be used for this.

cc @mjsqu

### PR DESCRIPTION
**Pull request by mjsqu**
Closes #163

### CODE REVIEW

**Comment by mjsqu** [comment]
Thanks for the suggestion @edgarrmondragon - open to discussion about which streams should be default. I deselected all the new ones, plus `runs` which is about 500,000 at our site. This leaves `accounts`, `jobs` and `projects`.

**Comment by edgarrmondragon** [comment]
> Thanks for the suggestion @edgarrmondragon - open to discussion about which streams should be default. I deselected all the new ones, plus `runs` which is about 500,000 at our site. This leaves `accounts`, `jobs` and `projects`.

Thanks @mjsqu! I think it makes sense to deselect all the new ones. However, doing it for `run` would be a breaking change (users that rely on default selection would suddenly stop syncing the stream) so I'd prefer that we leave it as is. Wdyt?

**Comment by mjsqu** [comment]
Agree with your comments about the `RunsStream` and it being a breaking change. We'll be pulling it anyway, so makes sense to have it selected by default for us too. Cheers! 👍

**Comment by mjsqu** [comment]
And doing the doco update now

**Comment by mjsqu** [comment]
Hmm - wasn't expecting my update to `README.md` to trigger another tap test - have I made an error in my update to the `.github/workflows/test-tap.yml` file?

**Comment by edgarrmondragon** [comment]
> Hmm - wasn't expecting my update to `README.md` to trigger another tap test - have I made an error in my update to the `.github/workflows/test-tap.yml` file?

@mjsqu I'm not too familiar with the behavior of `paths` and `paths-ignore` in github workflows but perhaps those changes only apply to PRs _after_ this one's merged 🤷‍♂️

**Comment by edgarrmondragon** [comment]
Thanks @mjsqu!

**Pull request merged**
